/* race.h.  Generated originally from race.h.in by configure, but pre-packed in os_macosx/ for Xcode builds. */
#define CONFIG_MACOSX 1
#define HAVE_DIRENT_H 1
#define HAVE_GETENV 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIBM 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_MKDIR 1
#define CONFIG_DATADIR "Contents/Resources"

/* version.h is auto-generated by an Xcode build step and dropped into the $DERIVED_FILE_DIR directory, which is part of the user search path. */
#include "version.h"
